[package]
name = "aoc"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
fixedbitset = "0.1.9"
itertools = "0.8.0"
lazy_static = "1.2.0"
regex = "1"
reqwest = "0.9.5"
rust-crypto = "^0.2"
